export enum Homework3Event {
	PLAY_GAME = "PLAY_GAME",
	CONTROLS = "CONTROLS",
	ABOUT = "ABOUT",
	MENU = "MENU",

	PLAYER_DAMAGE = "PLAYER_DAMAGE",
	PLAYER_I_FRAMES_END = "PLAYER_I_FRAMES_END",
	PLAYER_DEAD = "PLAYER_DEAD",
	SHOOT_BULLET = "SHOOT_BULLET",
	BULLET_USED = "BULLET_USED"
}

export enum Homework3Shaders {
	GRADIENT_CIRCLE = "GRADIENT_CIRCLE",
	LINEAR_GRADIENT_CIRCLE = "LINEAR_GRADIENT_CIRCLE"
}

export enum Homework3Animations {
	CAR_IDLE = "idle",
	CAR_BOOST = "boost",
	CAR_DIE = "explode"
}